@startuml ucd-v1
left to right direction
skinparam usecase {
  BackgroundColor darkcyan
  BorderColor darkcyan
  FontColor white
}

skinparam arrow {
    ArrowColor black
    Thickness 1.7
}

skinparam Linetype linear
skinparam Padding 10

actor "Master" as master

package "Usuários" {
    actor "Administrador" as admin
    actor "Contador" as contador
    actor "Visitante" as visitante
}

' Master engloba todos os usuários de administração
admin --|> master
contador --|> master

' Exemplificando ação de login
rectangle "Login" as login {
    usecase "Efetuar login" as efetuarLogin
    usecase "Acessar plataforma administrativa" as acessarAdminitstrativo
    master -u-> (efetuarLogin)
    (efetuarLogin) -l-> (acessarAdminitstrativo) : <<include>>
}

' Exemplificando ações da área administrativa
rectangle "Plataforma Administrativa" as plataformaAdministrativa {
    usecase "Gerenciar funcionários" as gerenciarFuncionarios
    usecase "Visualizar relatórios e gráficos" as relatoriosGraficos
    usecase "Gerenciar contas a pagar/receber" as gerenciarContas
    usecase "Gerenciar serviços" as gerenciarServicos
    usecase "Gerar NFs" as gerarNFs
    usecase "Gerenciar exposições" as gerenciarExposicoes
    admin -u-> (gerenciarFuncionarios)
    (gerenciarFuncionarios) .u.> (acessarAdminitstrativo) : <<extend>>
    admin -u-> (gerenciarExposicoes)
    (gerenciarExposicoes) .u.> (acessarAdminitstrativo) : <<extend>>
    admin -u-> (gerenciarServicos)
    (gerenciarServicos) .u.> (acessarAdminitstrativo) : <<extend>>
    adm -u-> (relatoriosGraficos)
    (acessarAdminitstrativo) <.u. (relatoriosGraficos) : <<extend>>
    adm -u-> (gerenciarContas)
    (acessarAdminitstrativo) <.u. (gerenciarContas) : <<extend>>
    contador -u-> (gerarNFs)
    (gerarNFs) .u.> (acessarAdminitstrativo) : <<extend>>
}

' Exemplificando ações da plataforma
rectangle "Plataforma" as plataforma {
    usecase "Acessar plataforma" as acessarPlataforma
    usecase "Agendar serviços" as agendarServicos
    usecase "Entrar em contato" as contato
    visitante -d-> (acessarPlataforma)
    (acessarPlataforma) <.d. (agendarServicos) : <<extend>>
    (acessarPlataforma) <.d. (contato) : <<extend>>
}

@enduml
